import "../globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import ManageShowGetReady from "@/utilities/ManageShowGetReady";
import ManageShowBanner from "@/utilities/ManageShowBanner";
import ManageNav from "@/utilities/ManageNav";

export const metadata = {
  title: "Klear",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ManageNav/>
        <ManageShowBanner />
        <main className="bodyCantainer mx-5 lg:mx-auto">{children}</main>
        <ManageShowGetReady />
        <Footer />
      </body>
    </html>
  );
}