import "../../globals.css";
import DashboardNav from "@/components/Dashbord/DashboardNav/DashboardNav";

export const metadata = {
  title: "Klear",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-5">
          <DashboardNav />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
