import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import TryCalculator from "@/components/shared/Buttons/TryCalculator";
import GetStarted from "@/components/GetStarted/GetStarted";
import ManageShowFeatures from "@/utilities/ManageShowGetReady";
import ManageShowGetReady from "@/utilities/ManageShowGetReady";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Klear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div className="bodyCantainer mx-auto">
          <Navbar/>
          {children}
        </div>
        <ManageShowGetReady/>
        <Footer />
      </body>
    </html>
  );
}
