import "../globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import ManageShowGetReady from "@/utilities/ManageShowGetReady";
import ManageShowBanner from "@/components/LandingPage/ManageShowBanner";

export const metadata = {
  title: "Klear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ManageShowBanner />
        <main className="bodyCantainer mx-auto">{children}</main>
        <ManageShowGetReady />
        <Footer />
      </body>
    </html>
  );
}
